## numpy

In [ ]:
import numpy as np


In [2]:
# benefit memory consumption
import sys
list1=list(range(1,101))
list1

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [4]:
sys.getsizeof(list1[0])

28

In [6]:
sys.getsizeof(list1[0])*len(list1)

2800

In [10]:
import numpy as np
arr=np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [12]:
arr.itemsize

4

In [14]:
arr.size

100

In [16]:
arr.nbytes

400

In [91]:
# benefit fast computation
list1=list(range(100))
list2=list(range(100))
for x,y in zip(list1,list2):
    print(x,y)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11
12 12
13 13
14 14
15 15
16 16
17 17
18 18
19 19
20 20
21 21
22 22
23 23
24 24
25 25
26 26
27 27
28 28
29 29
30 30
31 31
32 32
33 33
34 34
35 35
36 36
37 37
38 38
39 39
40 40
41 41
42 42
43 43
44 44
45 45
46 46
47 47
48 48
49 49
50 50
51 51
52 52
53 53
54 54
55 55
56 56
57 57
58 58
59 59
60 60
61 61
62 62
63 63
64 64
65 65
66 66
67 67
68 68
69 69
70 70
71 71
72 72
73 73
74 74
75 75
76 76
77 77
78 78
79 79
80 80
81 81
82 82
83 83
84 84
85 85
86 86
87 87
88 88
89 89
90 90
91 91
92 92
93 93
94 94
95 95
96 96
97 97
98 98
99 99


In [139]:

start=time.time()
sum1=[x+y for x,y in zip(list1,list2)]
end=time.time()
print('list time:',end-start)

list time: 0.0


In [121]:
arr1=np.arange(100)
arr2=np.arange(100)
start=time.time()
arr3=arr1+arr2
end=time.time()
print('list time',end-start)

list time 0.010000228881835938


In [170]:
# create empty array
arr1=np.array([])
arr1

array([], dtype=float64)

In [172]:
arr1=np.append(arr1,[1,2,3])
arr1

array([1., 2., 3.])

In [174]:
arr1=np.insert(arr1,2,10)
arr1

array([ 1.,  2., 10.,  3.])

In [176]:
arr1=np.insert(arr1,2,[20,15])
arr1

array([ 1.,  2., 20., 15., 10.,  3.])

In [191]:
arr1=np.delete(arr1,2)
arr1

array([ 1.,  2., 10.,  3.,  1.,  2.,  3.])

In [199]:
arr2=np.array([],dtype=int)
arr2=np.append(arr2,[1,2,3])
arr2

array([1, 2, 3])

In [201]:
arr2=np.insert(arr2,1,20)
arr2

array([ 1, 20,  2,  3])

In [203]:
arr2=np.delete(arr2,1)
arr2

array([1, 2, 3])

In [7]:
# 1D array
import numpy as np
arr1=np.array([1,2,5,10,15,25])
print(arr1)
print(type(arr1))
arr1

[ 1  2  5 10 15 25]
<class 'numpy.ndarray'>


array([ 1,  2,  5, 10, 15, 25])

In [5]:
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.itemsize)
print(arr1.nbytes)
print(arr1.dtype)

1
6
(6,)
4
24
int32


In [19]:
# 2D array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
print(arr2.size)
print(arr2.itemsize)
print(arr2.nbytes)
     

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
int32
9
4
36


In [25]:
# 3D array
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print(arr3.dtype)
print(arr3.size)
print(arr3.itemsize)
print(arr3.nbytes)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
int32
12
4
48


In [43]:
# arr[index]
arr1=np.array([1,2,5,10,15,25])
print(arr1[3])
print(arr1[-1])
print(arr1[::-1])

10
25
[25 15 10  5  2  1]


In [35]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2[1,1]

5

In [37]:
arr2[0,-1]

3

In [45]:
arr2[2,1]

8

In [57]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [59]:
arr3[0,0,1]

2

In [61]:
arr1=np.array([1,2,5,10,15,25])
arr1[3:6:1]

array([10, 15, 25])

In [63]:
arr1[-1:-4:-1]

array([25, 15, 10])

In [65]:
arr1[::-1]

array([25, 15, 10,  5,  2,  1])

In [67]:
arr1[::2]

array([ 1,  5, 15])

In [69]:
arr1[-3:-1]

array([10, 15])

In [73]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2[0,1:]

array([2, 3])

In [75]:
arr2[:,1]

array([2, 5, 8])

In [77]:
arr2[:,2]

array([3, 6, 9])

In [79]:
arr2[:,0]

array([1, 4, 7])

In [87]:
arr2[1,0:3:2]

array([4, 6])

In [91]:
arr2[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [93]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3[0,0,:]

array([1, 2, 3])

In [97]:
arr3[0,1,0]

4

In [99]:
arr3[1,1,1:]

array([11, 12])

In [101]:
arr3[0,:,:2]

array([[1, 2],
       [4, 5]])

In [103]:
arr3[0,1,::-1]

array([6, 5, 4])

In [105]:
arr3[:,1,::2]

array([[ 4,  6],
       [10, 12]])

In [113]:
# bulit-in methods
a=np.zeros(3,dtype=int)
a

array([0, 0, 0])

In [117]:
# 2D
b=np.zeros((3,3),dtype=int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [121]:
b[0,:]=[1,2,3]
b

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [123]:
b[:,:]=[1,2,3]
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [125]:
# 3D
c=np.zeros((3,2,3),dtype=int)
c

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [127]:
d=np.ones(3,dtype=int)
d

array([1, 1, 1])

In [129]:
e=np.ones((3,3),dtype=int)
e

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [131]:
f=np.ones((3,2,3),dtype=int)
f

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [9]:
# identity
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [21]:
# eye
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [143]:
# full
np.full((3,2,2),100)

array([[[100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100]]])

In [149]:
a=np.full((3,2,3),[[10,50,100],[1,2,3]])
a

array([[[ 10,  50, 100],
        [  1,   2,   3]],

       [[ 10,  50, 100],
        [  1,   2,   3]],

       [[ 10,  50, 100],
        [  1,   2,   3]]])

In [161]:
# reshape function
s=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
s

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [163]:
s.reshape((2,2,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [165]:
s.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [173]:
# resize 
np.resize(s,(3,2,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [175]:
# arange(start,stop,step)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [181]:
np.arange(1,11,2.5)

array([1. , 3.5, 6. , 8.5])

In [200]:
# linspace
np.linspace(1,5,10,retstep=True)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
        3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]),
 0.4444444444444444)

In [202]:
np.linspace(5,25,10,retstep=True)

(array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
        16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ]),
 2.2222222222222223)

In [208]:
# broadcasting-it is a mechanism that allows numpy to perform element-wise operations on arrays of different shape.
a=np.array([1,2,3])
print(a+10)
print(a*10)
print(a-10)
print(a/10)
print(a//10)
print(a**10)
print(a%10)

[11 12 13]
[10 20 30]
[-9 -8 -7]
[0.1 0.2 0.3]
[0 0 0]
[    1  1024 59049]
[1 2 3]


In [214]:
# vectorized operation
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [219]:
# max,min,argmax,argmin,unique
a=np.arange(10,50,7)
a

array([10, 17, 24, 31, 38, 45])

In [221]:
max(a)

45

In [223]:
min(a)

10

In [227]:
np.argmax(a)

5

In [229]:
np.argmin(a)

0

In [231]:
b=np.array([1,2,5,2,1,9])
b

array([1, 2, 5, 2, 1, 9])

In [233]:
np.unique(b)

array([1, 2, 5, 9])

In [1]:
# filtering condition
import numpy as np
arr1=np.array([1,2,1010,4,108,18,71,610])
arr1

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [3]:
arr1<100

array([ True,  True, False,  True, False,  True,  True, False])

In [5]:
np.where(arr1<100)

(array([0, 1, 3, 5, 6], dtype=int64),)

In [7]:
arr1[np.where(arr1<100)]

array([ 1,  2,  4, 18, 71])

In [9]:
arr1[arr1<100]

array([ 1,  2,  4, 18, 71])

In [13]:
arr2=np.array([True,True,False,False])
print(arr2.dtype)

bool


In [17]:
arr2[arr2==True]

array([ True,  True])

In [19]:
np.where(arr2==True)

(array([0, 1], dtype=int64),)

In [25]:
arr1=np.array([1,2,1010,4,108,18,71,610])
arr1[arr1>100]=10
arr1

array([ 1,  2, 10,  4, 10, 18, 71, 10])

In [32]:
# sorting
arr1=np.array([1,2,1010,4,108,18,71,610])
arr1.sort()
arr1

array([   1,    2,    4,   18,   71,  108,  610, 1010])

In [34]:
arr1[::-1] # here, we cant use reverse command

array([1010,  610,  108,   71,   18,    4,    2,    1])

In [36]:
# 2D ARRAY
arr2=np.array([[67,23,90,78,12],[65,20,79,63,92]])
arr2.sort(axis=0)
arr2

array([[65, 20, 79, 63, 12],
       [67, 23, 90, 78, 92]])

In [38]:
arr2.sort(axis=1)
arr2

array([[12, 20, 63, 65, 79],
       [23, 67, 78, 90, 92]])

In [40]:
# fancy indexing
# ->set-up matrix
a=np.zeros((10,10),dtype=int)
a


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
for i in range(10):
    a[i]=i+1

print(a)



[[ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4]
 [ 5  5  5  5  5  5  5  5  5  5]
 [ 6  6  6  6  6  6  6  6  6  6]
 [ 7  7  7  7  7  7  7  7  7  7]
 [ 8  8  8  8  8  8  8  8  8  8]
 [ 9  9  9  9  9  9  9  9  9  9]
 [10 10 10 10 10 10 10 10 10 10]]


In [54]:
a[[6,3,8]] # for rows

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [60]:
a[:,[1,4,8]] # for columns

array([[ 1,  1,  1],
       [ 2,  2,  2],
       [ 3,  3,  3],
       [ 4,  4,  4],
       [ 5,  5,  5],
       [ 6,  6,  6],
       [ 7,  7,  7],
       [ 8,  8,  8],
       [ 9,  9,  9],
       [10, 10, 10]])

In [62]:
arr1=np.array(range(1,17))
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [72]:
b=arr1.reshape((4,4))
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [74]:
b[[0,1,2,3],[0,1,2,3]]


array([ 1,  6, 11, 16])

In [76]:
# random numbers
from numpy import random
r=random.random(size=(4,5))
r

array([[0.42748321, 0.51406357, 0.25738707, 0.55040952, 0.53383025],
       [0.60667968, 0.37192737, 0.68719741, 0.63102841, 0.99814339],
       [0.15482882, 0.55045055, 0.48198234, 0.37342116, 0.53878283],
       [0.80190249, 0.1118137 , 0.76099078, 0.24966106, 0.2489908 ]])

In [78]:
s=random.randint(50,100,size=(4,5))
s

array([[90, 73, 86, 84, 54],
       [52, 80, 82, 51, 90],
       [70, 58, 79, 58, 95],
       [89, 72, 66, 91, 82]])

In [82]:
d=random.choice([90,10,110],p=[0.3,0.6,0.1],size=(3,3)) # p is probability
d

array([[ 90,  10,  10],
       [ 10,  10,  10],
       [ 90, 110,  10]])

In [90]:
import numpy as np
a=np.random.seed(123)# 123 default
b=np.random.randint(1,100,20)
b

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48, 74, 33, 47, 97, 26, 84, 79,
       37, 97, 81])

In [100]:
r=random.randint(0,255)
g=random.randint(0,255)
b=random.randint(0,255)
print(r,g,b) # check the result to get the colour through color picker website

47 248 189


In [110]:
arr4=np.array([90,23,89])
arr5=np.array([45,89,21])
arr6=np.array([45,89,21])
print(np.add(arr4,arr5,arr6))
print(np.subtract(arr4,arr5,arr6))
print(np.multiply(arr4,arr5,arr6))
print(np.divide(arr4,arr5))
print(np.divmod(arr4,arr5,arr6))

[135 112 110]
[ 45 -66  68]
[4050 2047 1869]
[2.         0.25842697 4.23809524]
(array([2, 0, 4]), array([ 0, 23,  5]))


In [130]:
arr4=np.array([10,20,30])
arr5=np.array([10,20,30])
print(np.sum([arr4,arr5],axis=0))
print(np.diff([arr4,arr5],n=1,axis=0))
print(np.product([arr4,arr5],axis=0))

[20 40 60]
[[0 0 0]]
[100 400 900]


In [134]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [136]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
import numpy as np
np.full((3,2,3),5)

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [9]:
a=np.array([1,2,3,4,5])
b=a.reshape(5,1)
b[::-1]

array([[5],
       [4],
       [3],
       [2],
       [1]])

In [1]:
import numpy as np
from numpy import random
arr1=np.random.randint(1,20,16)
arr1

array([ 6, 10,  5, 18,  7,  6, 12,  8, 10,  8, 17, 12,  3,  1,  2,  9])

In [3]:
arr2=arr1.reshape(2,2,4)
arr2

array([[[ 6, 10,  5, 18],
        [ 7,  6, 12,  8]],

       [[10,  8, 17, 12],
        [ 3,  1,  2,  9]]])

In [7]:
arr2.sort(axis=1) # for 3D array : (layers is 0,rows is 1,columns is 2)
arr2

array([[[ 6,  6,  5,  8],
        [ 7, 10, 12, 18]],

       [[ 3,  1,  2,  9],
        [10,  8, 17, 12]]])

In [9]:
arr2.sort(axis=2) # for 3D array : (layers is 0,rows is 1,columns is 2)
arr2

array([[[ 5,  6,  6,  8],
        [ 7, 10, 12, 18]],

       [[ 1,  2,  3,  9],
        [ 8, 10, 12, 17]]])

In [40]:
from datetime import date
a=date.today()
a

datetime.date(2024, 10, 11)

In [59]:
c=date(2003,1,4)
print(c)

2003-01-04


In [20]:
a.year

2024

In [22]:
a.month

10

In [24]:
a.day

11

In [61]:
c.isoweekday()

6

In [28]:
from datetime import datetime as dt
b=dt.now()
b

datetime.datetime(2024, 10, 11, 19, 47, 55, 967065)

In [30]:
b.minute

47

In [34]:
b.second

55

In [36]:
b.hour

19